project:
  type: website
  output-dir: _site
  preview:
    port: 4400
execute:
  freeze: true
website:
  title: "commonmeta-ruby"
  navbar:
    left:
      - href: index.qmd
        text: Guide
    tools:
      - icon: github
        href: https://github.com/front-matter/commonmeta-ruby
  page-footer:
    left: "Copyright &copy;2023 Front Matter."
    right:
      - icon: envelope
        href: mailto:info@front-matter.io
      - icon: mastodon 
        href: https://rogue-scholar.social/@admin

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme.scss]
    page-layout: article
    toc: true
    toc-location: left
