project:
  type: website
  output-dir: _site
  preview:
    port: 4400
execute:
  freeze: true
website:
  title: "commonmeta-ruby"
  favicon: favicon.ico
  bread-crumbs: false
  navbar:
    background: light
    logo: "/images/icon.png"
    logo-alt: "commonmeta-py"
    right:
      - icon: github
        href: https://github.com/front-matter/commonmeta-ruby
  sidebar:
    contents:
      - index.qmd
      - section: "Readers"
        contents: "readers/*.ipynb"
      - section: "Writers"
        contents: "writers/*.ipynb"
      - section: "Utils"
        contents: "utils/*.ipynb"
  page-footer:
    left: "Copyright &copy;2023 Front Matter."
    right:
      - icon: envelope
        href: mailto:info@front-matter.io
      - icon: mastodon 
        href: https://rogue-scholar.social/@admin

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme.scss]
    code-fold: false
    code-block-bg: true
    code-block-border-left: "#38a169"
    highlight-style: github
    toc: true
    toc-location: right
