name: Build Ruby Gem

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Build and test
      run: |
        gem install bundler
        bundle install
        bundle exec rspec

    # - name: SonarCloud Scan
    #   uses: sonarsource/sonarcloud-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Notify Slack
      uses: adamkdean/simple-slack-notify@1.0.4
      with:
        channel: '#ops'
        username: 'GitHub Actions'
        color: 'good'
        text: 'A new version of the briard gem has been built.'

